import { afterEach, describe, expect, it, vi } from 'vitest';
import { defaultSave, migrateSave, SaveSystem } from './SaveSystem';
import { WorldStateRegistry } from './WorldStateRegistry';
const fixture=()=>{let value:string|null=null;const storage={getItem:()=>value,setItem:vi.fn((_key:string,data:string)=>{value=data;})};return {storage,set:(data:string)=>{value=data;}};};
afterEach(()=>vi.useRealTimers());
describe('versioned local save',()=>{
  it('defaults without writing or sharing mutable state',()=>{const f=fixture(),save=new SaveSystem(f.storage);expect(save.load()).toEqual(defaultSave());expect(f.storage.setItem).not.toHaveBeenCalled();const a=save.load();a.player.discoveries.push('anchor');expect(save.load().player.discoveries).toEqual([]);});
  it.each(['{oops','null','[]','{"version":99}'])('warns and recovers from %s',raw=>{const f=fixture(),warn=vi.fn();f.set(raw);expect(new SaveSystem(f.storage,warn).load()).toEqual(defaultSave());expect(warn).toHaveBeenCalledOnce();});
  it('merges missing fields and sanitizes invalid values',()=>{const data=migrateSave({version:1,gameTime:{simulationTime:-3,elapsed:null},global:{intensity:9,quality:'ULTRA'},player:{discoveries:['anchor','unknown','anchor']}});expect(data.gameTime).toEqual(defaultSave().gameTime);expect(data.player.discoveries).toEqual(['anchor']);expect(data.global.intensity).toBe(1);expect(data.global.quality).toBe('MEDIUM');});
  it('round trips player, worlds, time, weather and quality',()=>{const f=fixture(),save=new SaveSystem(f.storage),data=defaultSave();data.player.currentWorldId='FARM';data.lastSuccessfulWorld='FARM';data.player.currentSpawnId='farm_dock_arrival';data.player.lastTravelDestination='FARM';data.player.discoveries=['lighthouse','anchor'];data.worlds.HOME.discoveries=['lighthouse','anchor'];data.worlds.FARM.lastSimulatedGameTime=1234;data.gameTime.simulationTime=5432;data.global={storm:true,intensity:.8,quality:'HIGH'};expect(save.save(data)).toBe(true);expect(save.load()).toEqual(data);});
  it('restores last successful dock rather than a travel phase',()=>{const data=migrateSave({version:1,lastSuccessfulWorld:'FARM',player:{currentWorldId:'TRAVEL',currentSpawnId:'sailing_out'}});expect(data.player.currentWorldId).toBe('FARM');expect(data.player.currentSpawnId).toBe('farm_dock_arrival');});
  it('coalesces saves and reads the latest snapshot at flush time',()=>{vi.useFakeTimers();const f=fixture(),save=new SaveSystem(f.storage),data=defaultSave();for(let i=0;i<20;i++)save.schedule(()=>data);data.global.storm=true;vi.advanceTimersByTime(250);expect(f.storage.setItem).toHaveBeenCalledOnce();expect(save.load().global.storm).toBe(true);save.schedule(()=>data);save.flush(()=>data);vi.runAllTimers();expect(f.storage.setItem).toHaveBeenCalledTimes(2);});
  it('handles denied storage without crashing gameplay',()=>{const warn=vi.fn(),save=new SaveSystem({getItem(){throw Error('denied');},setItem(){throw Error('quota');}},warn);expect(save.load()).toEqual(defaultSave());expect(save.save(defaultSave())).toBe(false);expect(warn).toHaveBeenCalledTimes(2);});
  it('isolates world snapshots from live mutable state',()=>{const registry=new WorldStateRegistry(),state=registry.get('HOME');state.discoveries.push('anchor');registry.set('HOME',state);state.discoveries.push('chest');expect(registry.get('HOME').discoveries).toEqual(['anchor']);const next=new WorldStateRegistry();next.restore(JSON.parse(JSON.stringify(registry.snapshot())));expect(next.snapshot()).toEqual(registry.snapshot());});
});
